---
title: "Latent Growth Curve Models"
author: "Biostatistics Working Group"
---

```r  [codeBlock.r]

#| echo: FALSE # The content of this code block will not be shown when rendered
#| output: FALSE # Output from this code block will not be shown when rendered
#| cache: FALSE

# This code loads the data to be used for the example

library(tidyverse) # Collection of R packages for data science
library(lavaan) # Structural Equation Modeling in R

# Set the data path
data_path <- "/Users/shawes/ABCD/data/rds/abcd_5.0_rds/core-rds-5.0/non-imaging_excluding_nt_5.0.rds"

# Read the data
df <- readRDS(data_path)

# Create and mutate the dataframe
df_selected <- df %>%
    select(src_subject_id, eventname, anthroheightcalc, site_id_l, rel_family_id.x) %>%
    filter(eventname %in% c("baseline_year_1_arm_1", "1_year_follow_up_y_arm_1", "2_year_follow_up_y_arm_1", "3_year_follow_up_y_arm_1")) %>%
    # drop_na(anthroheightcalc) %>%
    arrange(src_subject_id, eventname) %>%
    mutate(
        src_subject_id = factor(src_subject_id),
        eventname = factor(eventname, levels = c("baseline_year_1_arm_1", "1_year_follow_up_y_arm_1", "2_year_follow_up_y_arm_1", "3_year_follow_up_y_arm_1"), labels = c("Baseline", "Year_1", "Year_2", "Year_3")),
        anthroheightcalc = round(as.numeric(anthroheightcalc), 2),
        site_id_l = factor(site_id_l),
        rel_family_id.x = as.factor(rel_family_id.x)
    ) %>%
    rename(
        id = src_subject_id,
        event = eventname,
        height = anthroheightcalc,
        site = site_id_l,
        family = rel_family_id.x
    ) %>%
    group_by(id) %>%
    filter(all(c("Baseline", "Year_1", "Year_2", "Year_3") %in% event)) %>%
    fill(family, .direction = "downup") %>%
    ungroup()

# Remove duplicate family members

set.seed(123) # For reproducibility

# Filter to baseline event
df_baseline <- df_selected %>%
    filter(event == "Baseline")

# Identify families with multiple members at baseline
multi_member_families <- df_baseline %>%
    group_by(family) %>%
    filter(n() > 1) %>%
    ungroup()

# Randomly select one member per family with multiple members at baseline
selected_multi_members <- multi_member_families %>%
    group_by(family) %>%
    sample_n(1) %>%
    ungroup()

# Identify families with a single member at baseline
single_member_families <- df_baseline %>%
    group_by(family) %>%
    filter(n() == 1) %>%
    ungroup()

# Combine the selected single members and randomly selected multi-members
selected_families <- bind_rows(single_member_families, selected_multi_members)

# Extract the ids of the selected individuals
selected_ids <- selected_families$id

# Filter the original dataset to include only the selected individuals
df_long <- df_selected %>%
    filter(id %in% selected_ids)

```

## Overview
Latent growth curve models (LGCM) are an analytical tool within the framework of structural equation modeling that enable the examination of change over time. This model type effectively separates the true trajectory of a variable from random measurement error, allowing for the estimation of an underlying growth process. The primary components of LGCM include the intercept, which represents the initial status, and the slope, which reflects the rate of change over time.

This example investigates a growth trajectory of participant's height, measured across 4 annual assessments in participants from the ABCD Study. Fitting the latent growth curve model will allow for an examination of the initial status (intercept) and rate of change (slope) of height from baseline through successive yearly follow-ups. Each participant's height trajectory is modeled to capture both the starting point and the growth pattern over time. The results are illustrated through growth plots that demonstrate the mean trajectory across the cohort, along with the variability in growth rates among individuals, providing insights into the developmental patterns of height over time.

## Results 
### Compute Latent Growth Curve Model
The code below is used to compute a growth curve model to investigate changes in height across four annual assessments. This statistical approach provides insights into how much individuals vary around the average trajectory and the consistency of their growth patterns across time. This model estimates an overall intercept, representing the initial status, and a slope that captures the rate of growth across time points. 

```r  [codeBlock.r]

# Convert to wide format if necessary
df_wide <- df_long %>%
    pivot_wider(names_from = event, values_from = c(height), names_prefix = "Height_")

model <- " i =~ 1*Height_Baseline + 1*Height_Year_1 + 1*Height_Year_2 + 1*Height_Year_3
           s =~ 0*Height_Baseline + 1*Height_Year_1 + 2*Height_Year_2 + 3*Height_Year_3

           # Intercept and slope variances
           i ~~ i
           s ~~ s

           # Residual variances for each observed variable
           Height_Baseline ~~ var_baseline*Height_Baseline
           Height_Year_1 ~~ var_year1*Height_Year_1
           Height_Year_2 ~~ var_year2*Height_Year_2
           Height_Year_3 ~~ var_year3*Height_Year_3
"

fit <- growth(model, data = df_wide, cluster = "site", missing = "fiml")
summary(fit)
```

The results from the latent growth curve analysis show an increasing pattern of mean change in participant's height across assessments (slope = 2.463, p<.001). In addition, the model identified significant variability in both the intercept (estimate = 8.939, se = 0.202, p<.001), which represents initial height, and the slope (estimate = 0.419, se = 0.064, p<.001), which measures growth over time. This indicates substantial differences in starting heights and growth rates among individuals. The covariance between the intercept and slope was statistically significant (estimate = -0.129, p = 0.037), suggesting that higher initial heights are associated with lower growth rates.

### Model Plots
```r  [codeBlock.r]

selected_ids <- sample(unique(df_long$id), 150)

df_long_selected <- df_long[df_long$id %in% selected_ids, ] # Filter the data to include only the selected participants

# Plotting the height data over time from the df_long dataframe
ggplot(df_long_selected, aes(x = event, y = height, group = id)) +
    geom_line(alpha = 0.4, aes(color = "Actual Height"), linewidth = 0.5) + # Lines to connect data points for each participant
    geom_point(alpha = 0.6, color = "blue") + # Points for actual heights
    scale_x_discrete(limits = c("Baseline", "Year_1", "Year_2", "Year_3")) + # Ensuring the order of events
    labs(
        title = "Actual Height Growth Across Timepoints",
        x = "Time (Years from Baseline)",
        y = "Height (inches)"
    ) +
    theme_minimal() +
    theme(legend.position = "bottom") # Adjust legend position

```

This plot visualizes the height trajectories across four annual timepoints. Each line represents an individual participant's height trajectory showing overall trends while maintaining focus on individual variations. Blue points mark the actual height measurements at each timepoint, providing a clear view of the data distribution and growth patterns over time. This graph highlights both the general trend of increasing height and the individual differences in growth rates among participants.

## Wrapping Up
This analysis employed a latent growth curve model (LGCM) framework to examine participants' heights across multiple assessment points. Results revealed an increasing trend in average height changes over time, with a slope parameter of 2.46 (p<.001), indicating a steady growth across all assessments. Significant variability was observed both in the intercept, with an estimate of 8.94 (se = 0.20, p<.001), representing the initial height, and in the slope, with an estimate of 0.42 (se = 0.06, p<.001), which measures growth over time. This highlights notable individual differences in starting heights and growth rates. Furthermore, the significant covariance between the intercept and slope (estimate = -0.13, p = 0.037) suggests that higher initial heights are associated with lower subsequent growth rates.

Latent growth curve modeling provides a powerful tool for evaluating patterns of growth, allowing for the differentiation between average growth trajectories and individual variability. This method is able to parse out complex relationships, underscoring its utility in longitudinal data analysis, enhancing our interpretation of how individuals change over time.


