# https://github.com/actions/deploy-pages#usage
name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Enable Corepack (for modern package management)
      - run: corepack enable

      # Setup Node.js environment
      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      # Ensure NUXT_UI_PRO_LICENSE is available during build
      - name: Setup environment variables
        run: echo "NUXT_UI_PRO_LICENSE=${{ secrets.NUXT_UI_PRO_LICENSE }}" >> $GITHUB_ENV

      # Install dependencies with npm
      - name: Install dependencies
        run: npm ci

      # Build the project using the GitHub Pages preset
      - name: Build project
        run: npx nuxt build --preset github_pages

      # Upload artifact for deployment
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.output/public

  deploy:
    # Add a dependency on the build job
    needs: build

    # Grant GITHUB_TOKEN the necessary permissions
    permissions:
      pages: write
      id-token: write

    # Set deployment environment for GitHub Pages
    environment:
      name: github_pages
      url: ${{ steps.deployment.outputs.page_url }}

    # Deploy using the deploy-pages action
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
